name: Testing

on:
  push:
    branches:
      - "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/testing.yml"
      - "Makefile"
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/testing.yml"
      - "Makefile"

jobs:
  test:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.18", "1.19" ]
    steps:
    - name: Set up Go ${{ matrix.go }}.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache go module
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run test
      env:
        CGO_ENABLED: 1
      run: |
        go test -v -race -cover -covermode=atomic ./...

    - name: Run integration test
      run: make test-integration

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.*
